-- MySQL Script generated by MySQL Workbench
-- Mon 23 Oct 2017 02:52:54 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testex9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testex9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testex9` DEFAULT CHARACTER SET latin1 ;
USE `testex9` ;

-- -----------------------------------------------------
-- Table `testex9`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`endereco` (
  `idEndereco` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `numeroEndereco` INT(11) NULL DEFAULT NULL,
  `rua` VARCHAR(255) NULL DEFAULT NULL,
  `uf` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`usuario` (
  `idUsuario` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dtype` VARCHAR(1) NULL DEFAULT NULL,
  `CPF` VARCHAR(255) NULL DEFAULT NULL,
  `data_nascimento` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(14) NULL DEFAULT NULL,
  `idEndereco` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `FK_usuario_idEndereco` (`idEndereco` ASC),
  CONSTRAINT `FK_usuario_idEndereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `testex9`.`endereco` (`idEndereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`administrador` (
  `idAdministrador` BIGINT(20) NOT NULL,
  `cargo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministrador`),
  CONSTRAINT `FK_administrador_idAdministrador`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `testex9`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`relatorioParental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`relatorioParental` (
  `idRelatorioParental` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `criatividade` DOUBLE NULL DEFAULT NULL,
  `lideranca` DOUBLE NULL DEFAULT NULL,
  `motivacao` DOUBLE NULL DEFAULT NULL,
  `observacoes` VARCHAR(255) NULL DEFAULT NULL,
  `participacaoEmSala` DOUBLE NULL DEFAULT NULL,
  `trabalhoEmEquipe` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idRelatorioParental`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`turma` (
  `idTurma` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroSala` INT(11) NULL DEFAULT NULL,
  `qtdAluno` INT(11) NULL DEFAULT NULL,
  `serie` VARCHAR(255) NULL DEFAULT NULL,
  `turno` VARCHAR(255) NULL DEFAULT NULL,
  `idProfessor` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `FK_turma_idProfessor` (`idProfessor` ASC),
  CONSTRAINT `FK_turma_idProfessor`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `testex9`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`aluno` (
  `idAluno` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_nascimento` VARCHAR(255) NULL DEFAULT NULL,
  `deficiencia` VARCHAR(255) NULL DEFAULT NULL,
  `matricula` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `idResponsavel` BIGINT(20) NULL DEFAULT NULL,
  `idTurma` INT(11) NULL DEFAULT NULL,
  `idRelatorioParental` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `FK_aluno_idResponsavel` (`idResponsavel` ASC),
  INDEX `FK_aluno_idRelatorioParental` (`idRelatorioParental` ASC),
  INDEX `FK_aluno_idTurma` (`idTurma` ASC),
  CONSTRAINT `FK_aluno_idRelatorioParental`
    FOREIGN KEY (`idRelatorioParental`)
    REFERENCES `testex9`.`relatorioParental` (`idRelatorioParental`),
  CONSTRAINT `FK_aluno_idResponsavel`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `testex9`.`usuario` (`idUsuario`),
  CONSTRAINT `FK_aluno_idTurma`
    FOREIGN KEY (`idTurma`)
    REFERENCES `testex9`.`turma` (`idTurma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`professor` (
  `idProfessor` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idProfessor`),
  CONSTRAINT `FK_professor_idProfessor`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `testex9`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testex9`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testex9`.`responsavel` (
  `idResponsavel` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idResponsavel`),
  CONSTRAINT `FK_responsavel_idResponsavel`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `testex9`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
